version: '3.7'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - hotel-mongo
    network_mode: bridge

  hotel-mongo:
    image: mongo
    container_name: hotel-mongo
    ports:
      - 27017:27017
    volumes:
      - .:/home/node/app
    network_mode: bridge

